# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Twitter sync

on:
  workflow_dispatch:
  #schedule:
  #    - cron: '*/30 * * * *'  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'louisgrasset/touitomamout'
        ref: 'v1.7.0'
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: Cache
      uses: actions/cache@v4.0.2
      with:
        path: cache*json 
        key: cache-json 
    - name: Dummy .env file
      run: |
        echo TWITTER_HANDLE=${{ secrets.TWITTER_HANDLE }} >>.env
        echo TWITTER_USERNAME=${{ secrets.TWITTER_USERNAME }} >>.env
        echo TWITTER_PASSWORD=${{ secrets.TWITTER_PASSWORD }} >>.env
        echo MASTODON_INSTANCE=${{ secrets.MASTODON_INSTANCE }} >>.env
        echo MASTODON_ACCESS_TOKEN=${{ secrets.MASTODON_ACCESS_TOKEN }} >>.env
        echo SYNC_MASTODON=${{ secrets.SYNC_MASTODON }} >>.env
        echo BLUESKY_INSTANCE=${{ secrets.BLUESKY_INSTANCE }} >>.env
        echo BLUESKY_IDENTIFIER=${{ secrets.BLUESKY_IDENTIFIER }} >>.env
        echo BLUESKY_PASSWORD=${{ secrets.BLUESKY_PASSWORD }} >>.env
        echo SYNC_BLUESKY=${{ secrets.SYNC_BLUESKY }} >>.env

    - name: Sync
      run: node dist/index.js          
